### ISSUE TITLE
Virus Detected

### ISSUE THREAD

**Issue by eidleweise** [nymda/WinTerrEdit#11]
Hey there when I downloaded this I got a warning about Trojan:Win32/Zpevdo.B (see attached)

![image](https://user-images.githubusercontent.com/61235522/96028684-87e4f100-0e51-11eb-8917-d5d792cd1252.png)

**Comment by nymda** [comment]
This is a false positive, i have put a ticket in to have it resolved but its in Microsoft's hands. I think its due to the way i pack and extract assets like images, names, etc. For now, you can click actions and restore to get the file back and run it as normal. you can also try some older versions of the program as they are more well established.

**Comment by eidleweise** [comment]
Thanks for letting us know. I suspected it was something like that, but I figured it's best to reach out and confirm.

**Comment by nymda** [comment]
No problem, sorry about that

**Comment by eidleweise** [comment]
Is it worth mentioning this on the main page? Just to not alarm folks?

**Comment by nymda** [comment]
Ive done that before but its a pretty rare issue, putting a warning tends to alarm people more.

**Comment by nymda** [comment]
![image](https://user-images.githubusercontent.com/16545187/96228407-77399580-0f8d-11eb-8b14-1ce2073dfd70.png)
this has now been resolved by ms

**Comment by eidleweise** [comment]
That's a hell of a lot more responsive than I'd have expected of MS! This is great news
