### ISSUE TITLE
Virus warning on standalone release 

### ISSUE THREAD

**Issue by rastrof** [nymda/WinTerrEdit#6]
WTE-Standalone.exe is infected with Gen:Variant.Razy.692728 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.

**Comment by nymda** [comment]
Hello, this is a known false positive. I expect it is due to the large amount of embedded data WTE contains in order to load the item graphics or has something to do with the crypto functions. I can assure you it isnt actually malicious, though please compile from the source if you dont want to use the release downloads. 

I added a note to the release page incase anyone else has this issue, sorry it showed up for you, hopefully i can find a fix in the near future. 

if you can, please take a screenshot from bitdefender and attach it here, then i can submit it to them as a support ticket.

**Comment by nymda** [comment]
Bitdefender has responded and the detection will be removed in the next few updates.
